name: test
on: [push, pull_request]

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint for newline at the end of file
        uses: fernandrone/linelint@master
        id: linelint
      - name: Lint markdown files
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          config_file: .markdownlintrc
      - name: Notify Slack
        uses: 8398a7/action-slack@v3.1.0
        with:
          status: ${{ job.status }}
          fields: repo,commit,action,workflow,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
